### PR TITLE
Update example project

### PR DESCRIPTION
**Pull request by edwardloveall**
Not sure what's going on here but it seems like the renderer isn't actually doing a better job of rendering anything. In fact, it's doing a worse job if anything. The ellipse and circle don't render at all with the Shiva renderer.

### CODE REVIEW

**Comment by edwardloveall** [comment]
Here are some pictures:

screen shot 2015-10-13 at 8 47 08 pm

screen shot 2015-10-13 at 8 47 14 pm

**Comment by procedural** [comment]
@edwardloveall are you using openFrameworks 0.8.4?

**Comment by edwardloveall** [comment]
Yes.

**Comment by procedural** [comment]
@edwardloveall :) this fork is for upcoming openFrameworks 0.9.0 only.

Currently you can get it from here: https://github.com/openframeworks/openFrameworks
Or use these nightly builds: http://openframeworks.cc/versions/v0.9.0RC1/

**Comment by edwardloveall** [comment]
Ah ha! Gotcha, thanks!

**Pull request closed without merging**
